# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:2.7

EXPOSE 3111

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /techtrends
COPY ./techtrends /techtrends

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /techtrends
USER appuser

# Install pip requirements
RUN python -m pip install -r requirements.txt

# RUN db setup scripts
RUN python init_db.py

# Run
CMD ["python", "app.py"]
