namespace:
  name: demo
replicas: 3
image:
  name: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  cpu: 50m
  mem: 256Mi

service:
  port: 8111
  type: ClusterIP

configmap: "version:1.18.0"
