apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  name: techtrends  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: jesusarueda/techtrends:latest
        ports:
        - containerPort: 3111
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"       
          limits:
            cpu: "500m"
            memory: "128Mi"       
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111          
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111        
          initialDelaySeconds: 5
          periodSeconds: 10
        