##  Named of the workflow.
name: TechTrends - Package with Docker

defaults:
  run:    
    working-directory: project/

## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on: 
  push:
    branches:
      - master

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  package:
  
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed 
    steps:
      
      ## Executes the `python --version` command
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: jesusarueda
          password: 123
      - run: docker build . -t jesusarueda/techtrends      
      - run: docker push jesusarueda/techtrends



