##  Named of the workflow.
name: TechTrends - Package with Docker

## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on: 
  push:
    branches:
      - master

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  package:
    
    environment: udacity
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed 
    steps:
      - uses: actions/checkout@v1
      ## Executes the `python --version` command
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: project
          #file: dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/jesusarueda/techtrends:latest



